# Generated by Django 4.2.3 on 2023-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_posts_id_posts_idkun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='idkun',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
